version: '3'
services:
    db:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: demoticks 
          MYSQL_USER: demoticksAdmin
          MYSQL_PASSWORD: password
        ports:
          - "3306:3306"
        expose:
          - "3306" 
        container_name: demoticks_mysql
        networks: 
          - demoticks_net
        healthcheck:
          test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SHOW DATABASES;'"]
          interval: 5s
          timeout: 5s
    web:
        image: thebv/demoticks-node-app:latest
        #build: .
        environment: 
          DATABASE_URL: mysql://demoticksAdmin:password@demoticks_mysql:3306/demoticks
        external_links:
          - demoticks_mysql
        container_name: demoticks_web
        networks: 
          - demoticks_net
        ports:
          - "4351:4351"
        depends_on:
          db:
            condition: service_healthy
networks: 
    demoticks_net:
        internal: false