version: '3'
services:
    db:
        image: mysql:8.0
        volumes:
          - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: demoticks 
          MYSQL_USER: demoticksAdmin
          MYSQL_PASSWORD: password
        ports:
          - "3306:3306"
        expose:
          - "3306" 
        container_name: demoticks_mysql
        networks: 
          - demoticks_net
    web:
        image: thebv/demoticks-node-app:latest
        #build: .
        environment:
          - sqlHost=demoticks_mysql
        external_links:
          - demoticks_mysql
        container_name: demoticks_web
        networks: 
          - demoticks_net
        ports:
          - "4351:4351"
        depends_on:
          - "db"
networks: 
    demoticks_net:
        internal: false